name: ui_color
description: The color class from dart:ui in a standalone Dart package.
version: 1.20210214.0
homepage: https://github.com/hacker1024/ui_color.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.2
